version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3022
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - '3022:3022'
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=file:/app/data/app.db

volumes:
  data:
